### ISSUE TITLE
OTEL Metrics Collection : Batching & Label Processing

### ISSUE THREAD

**Issue by alexandreLamarre** [rancher/opni#1163]
Related to [OEP](https://github.com/rancher/opni/blob/main/enhancements/monitoring/20230117-move-to-otel-collector.md)

**Comment by alexandreLamarre** [comment]
Consider removing some host metrics for more streamlined processing
- processes
- filesystem
- disk merges

**Comment by alexandreLamarre** [comment]
not started, rolling over to sprint 4

**Comment by alexandreLamarre** [comment]
K8s resource attribute labels contain valuable data for downstream use, but for metrics we should drop container metadata and resource uid labels during processing on the node otel agents to reduce memory footprint

**Comment by alexandreLamarre** [comment]
since the `action` part of attribute processing process doesn't allow for matching keys to regex, we may need to "externalize" the portions of `k8s.*.uuid` into our struct that executes the templates

```
k8sattributes:
    passthrough: false
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: connection
```
to explicitly drop all relevant `_uid` labels on metrics.
```yaml
  attributes/k8smetrics:
    include:
      match_type: regexp
      metric_names : ["^k8s"]
      attributes:
      - key: k8s_pod_uid
#...
    actions:
#...
      - action: delete
        key: k8s_pod_uid
```
