### ISSUE TITLE
Otel metrics collector agent config error

### ISSUE THREAD

**Issue by kralicky** [rancher/opni#1444]
Otel collector agents for metrics are running into the following error when starting:
```
Error: invalid configuration: service::pipeline::metrics: must have at least one receiver
2023/05/25 19:24:34 collector server run finished with error: invalid configuration: service::pipeline::metrics: must have at least one receiver
```

config.yaml:
```

receivers: ${file:/etc/otel/receivers.yaml}
exporters:
  otlp:
    endpoint: "opni-otel-aggregator:4317"
    tls:
      insecure: true
    sending_queue:
      num_consumers: 4
      queue_size: 100
    retry_on_failure:
      enabled: true
processors:
  memory_limiter:
    limit_mib: 250
    spike_limit_mib: 50
    check_interval: 1s
  k8sattributes:
    passthrough: false
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.name
      - from: resource_attribute
        name: k8s.namespace.name
    - sources:
      - from: connection
    extract:
      metadata:
      - "k8s.deployment.name"
      - "k8s.statefulset.name"
      - "k8s.daemonset.name"
      - "k8s.cronjob.name"
      - "k8s.job.name"
      - "k8s.node.name"
      - "container.image.name"
      - "container.image.tag"
      labels:
      - key: tier
      - key: component
    
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["lookup"]
service:
  telemetry:
    metrics:
      level: none
  pipelines:
  
    metrics:
      receivers:
      processors: [memory_limiter, resourcedetection/system]
      exporters: [otlp]
```

receivers.yaml:
```

hostmetrics:
  root_path: /hostfs
  collection_interval: 15s
  scrapers:
    cpu: {}
    disk: {}
    load: {}
    processes: {}
    filesystem:
      exclude_fs_types:
        fs_types:
        - ^autofs$
        - ^binfmt_misc$
        - ^bpf$
        - ^cgroup2?$
        - ^configfs$
        - ^debugfs$
        - ^devpts$
        - ^devtmpfs$
        - ^fusectl$
        - ^hugetlbfs$
        - ^iso9660$
        - ^mqueue$
        - ^nsfs$
        - ^overlay$
        - ^proc$
        - ^procfs$
        - ^pstore$
        - ^rpc_pipefs$
        - ^securityfs$
        - ^selinuxfs$
        - ^squashfs$
        - ^sysfs$
        - ^tracefs$
        match_type: regexp
      exclude_mount_points:
        mount_points:
        - ^/dev(/|$)
        - ^/proc(/|$)
        - ^/sys(/|$)
        - ^/var/lib/docker/.+(/|$)
        - ^/var/lib/kubelet/.+(/|$)
        match_type: regexp
kubeletstats:
  collection_interval: 20s
  endpoint: "https://${HOST_IP}:10250"
  auth_type: "serviceAccount"
  insecure_skip_verify: true
```
