### ISSUE TITLE
Prometheus agent config file generates empty string for global.evaluation_interval key

### ISSUE THREAD

**Issue by kralicky** [rancher/opni#1469]
(v0.10.0-rc4 regression)
This causes prometheus agents to fail to start with:
```
ts=2023-06-01T21:11:10.112Z caller=main.go:468 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: empty duration string"
```
The config files in question contain:
```
global:
  evaluation_interval: ""
  scrape_interval: 30s
...
```
