### ISSUE TITLE
/amazon/opensearch-dashboards:1.1.0 not found: manifest unknown: manifest unknown 

### ISSUE THREAD

**Issue by Zakaria-laktati** [rancher/opni#170]
I am trying to deploy Opni on a private kubernetes environment using a proxy. I was able to push all the yaml files with no problem and while trying to deploy the elastic image I got the following message: **/amazon/opensearch-dashboards:1.1.0 not found: manifest unknown: manifest unknown** 

As I did for all the other images. I added the proxy before the image link and it didn't work.

my question is : can we change the source of the elastic image and how can we do this?
![image](https://user-images.githubusercontent.com/58961075/147368164-78b4bb37-d9e2-46a1-b23d-3f49c5c53c7b.png)

**Comment by kralicky** [comment]
Hi @Zakaria-laktati,
`defaultRepo` should contain the name of your private image registry, e.g.
```yaml
elastic:
  defaultRepo: your.image.registry/amazon
```

You can also specify the full image references as follows (this will override `defaultRepo` and `version`)
```yaml
elastic:
  image: your.private.registry/amazon/opensearch:tag
  kibanaImage: your.private.registry/amazon/opensearch-dashboards:tag
```

**Comment by Zakaria-laktati** [comment]
Regarding the first solution, it's the same thing I did at the beginning when I got the error: **/amazon/opensearch-dashboards:1.1.0 not found: manifest unknown: manifest unknown**

and when i tried to put the full image references like you suggested. I got the following error message: 
![image](https://user-images.githubusercontent.com/58961075/147389099-76edcedf-33cb-439b-b8ff-8420bda540b0.png)

thanks in advance

**Comment by kralicky** [comment]
Sorry, it should actually be:
```yaml
elastic:
  image: 
    image: your.private.registry/amazon/opensearch:tag
  kibanaImage: 
    image: your.private.registry/amazon/opensearch-dashboards:tag
```
