### ISSUE TITLE
Allow finer tuning of opentelemetry collectors

### ISSUE THREAD

**Issue by alexandreLamarre** [rancher/opni#1748]
We want to allow users to perform some fine tuning of the collectors deployed by opni agents, since these can be workload specific. 

A few of interest that are also simple to allow to configure come to mind:

## For the daemonset:

memory limit tuning

```
processors:
  memory_limiter:
    limit_mib: 250
    spike_limit_mib: 50
    check_interval: 1s
   // ....
```

For Logs OTLP exporters:

```
sending_queue:
      num_consumers: 4
      queue_size: 100
    retry_on_failure:
      enabled: true
```

## For the aggregator

generic processors:

```
batch:
    send_batch_size: 1000
    timeout: 15s
  memory_limiter:
    limit_mib: 1000
    spike_limit_mib: 350 
    check_interval: 1s
```

for logs exporting to agent 

```
exporters:
  otlphttp:
    endpoint: "{{ .AgentEndpoint }}"
    tls:
      insecure: true
    sending_queue:
      num_consumers: 4
      queue_size: 100
    retry_on_failure:
      enabled: true
```
