### ISSUE TITLE
Fail to build locally

### ISSUE THREAD

**Issue by jvanz** [rancher/opni#1829]
I'm new in the project and trying to build everything locally. After running the command `go run ./dagger --setup` and following the input requests I've ended with the following file

```yaml
charts:
    git:
        auth:
            email: ""
            username: ""
        branch: ""
        export: false
        push: false
        repo: ghcr.io/jvanz
    oci:
        auth:
            email: ""
            username: ""
        push: false
        repo: ghcr.io/jvanz
coverage:
    export: false
images:
    minimal:
        additional-tags: []
        auth:
            email: ""
            username: ""
        push: false
        repo: ghcr.io/jvanz
        tag: latest
        tag-suffix: -minimal
    opensearch:
        build:
            dashboards-version: 2.8.0
            opensearch-version: 2.8.0
            plugin-version: 0.12.0
        dashboards:
            additional-tags: []
            auth:
                email: ""
                username: ""
            push: false
            repo: ghcr.io/jvanz
            tag: latest
            tag-suffix: ""
        opensearch:
            additional-tags: []
            auth:
                email: ""
                username: ""
            push: false
            repo: ghcr.io/jvanz
            tag: latest
            tag-suffix: ""
        update-service:
            additional-tags: []
            auth:
                email: ""
                username: ""
            push: false
            repo: ghcr.io/jvanz
            tag: latest
            tag-suffix: ""
    opni:
        additional-tags: []
        auth:
            email: ""
            username: ""
        push: false
        repo: ghcr.io/jvanz
        tag: latest
        tag-suffix: ""
    python-base:
        additional-tags: []
        auth:
            email: ""
            username: ""
        push: false
        repo: ghcr.io/jvanz
        tag: latest
        tag-suffix: ""
    python-torch:
        additional-tags: []
        auth:
            email: ""
            username: ""
        push: false
        repo: ghcr.io/jvanz
        tag: latest
        tag-suffix: -torch
lint: false
releaser:
    arch: []
    auth:
        email: ""
        username: ""
    os: []
    push: false
    repo: ghcr.io/jvanz
    tag: latest
test: true
```

However, when I ran the command `dagger run go run ./dagger -c dagger/ci/defaults,dev/dagger --charts.git.export` it failed:

```
$ dagger run go run ./dagger -c dagger/ci/defaults,dev/dagger.yaml --charts.git.export
┣─╮ 
│ ▽ init
│ █ [1.11s] connect
│ ┣ [0.86s] starting engine
│ ┣ [0.21s] starting session
│ ┻ 
█ [0.60s] ERROR go run ./dagger -c dagger/ci/defaults,dev/dagger.yaml --charts.git.export
┃ incorrect types at key os, type []string != []interface {}                                                                                                                                                                                  
┃ exit status 1                                                                                                                                                                                                                               
┻ 
• Engine: 89e85dd7b6f0 (version v0.8.7)
⧗ 1.71s ✔ 3 ✘ 1
```

Turns out that the generated file has the fields `releaser.os` and `releaser.arch` empty values. Which causes the command to fail. Even the `--show-config` command fail with the same error.  I've tested with generated fails using `yaml` and `toml` format.

To workaround this issue, I must have to remove the `releaser.os` and `releaser.arch` fields from the generated file.

**Comment by alexandreLamarre** [comment]
Changing your command from `go run ./dagger -c dagger/ci/defaults,dev/dagger.yaml --charts.git.export` to 
`go run ./dagger -c dev/dagger.yaml --charts.git.export` should fix things.

For clarification, specifying multiple files attempts to merge them and the `dagger/ci/defaults` is attempting to build release binaries which are specified in another `dagger/ci/` file : 

The full CI command is `go run ./dagger -c dagger/ci/defaults,dagger/ci/push,dagger/ci/push-charts,dagger/ci/tag-latest,dagger/ci/tag-release --lint=false --test=false`, so you can update the values specified in those files to run the full build (release) process in a fork

---- 

For simple local builds you would typically use:
Charts: `go run ./dagger --charts.git.export`, to build the charts into a local `charts/` directory and
Pushing images : `go run ./dagger -c  <file>` whose contents would contain something like:
```
[images.opni]
additional-tags = []
push = true
repo = "docker.io/alex7285/opni"
tag = "patch"
tag-suffix = ""
```

**Comment by kralicky** [comment]
Thanks for reporting this, The setup tool is used infrequently so I'll see if I can make sure it always generates a working config. For reference, this is what my `dev/dagger.toml` looks like:
```toml

[charts.git]
	repo = "github.com/kralicky/opni"
[charts.git.auth]
	email = "joe.kralicky@suse.com"
	username = "kralicky"

[charts.oci]
	repo = "docker.io"

[charts.oci.auth]
	username = "kralicky"

[images.opni]
	repo = "docker.io/kralicky/opni"
	tag = "latest"
	push = true
[images.opni.auth]
	username = "kralicky"

[images.minimal]
	repo = "docker.io/kralicky/opni"
	tag = "latest"
	push = true
[images.minimal.auth]
	username = "kralicky"
```

Some example usages:
1. building development images and updating a live cluster:
```bash
dagger run go run ./dagger -c dagger/ci/defaults,dev/dagger --test=false --lint=false
kubectl -n opni rollout restart deployment opni-manager
kubectl -n opni rollout status deployment opni-manager --watch
```
2. building local charts (no config required):
```bash
dagger run go run ./dagger --charts.git.export
```
3. Updating the dagger CLI (to the matching version in go.mod)
```bash
mage dagger:install
```
4. Running all tests in the CI environment (no config required)
```bash
dagger run go run ./dagger --test --lint
```
Note that for building, testing, etc. in cases where you don't need to build actual image/chart artifacts, you would normally use `mage` to run everything locally.
