### ISSUE TITLE
Cortex AIO won't run on EKS cluster

### ISSUE THREAD

**Issue by dbason** [rancher/opni#596]
Seems to be issues with the file system.
Config:
```
auth_enabled: true
api:
    response_compression_enabled: true
    prometheus_http_prefix: /prometheus
server:
    http_listen_port: 8080
    grpc_listen_port: 9095
    http_tls_config:
        cert_file: /run/cortex/certs/server/tls.crt
        key_file: /run/cortex/certs/server/tls.key
        client_auth_type: RequireAndVerifyClientCert
        client_ca_file: /run/cortex/certs/client/ca.crt
    grpc_tls_config:
        cert_file: /run/cortex/certs/server/tls.crt
        key_file: /run/cortex/certs/server/tls.key
        client_auth_type: RequireAndVerifyClientCert
        client_ca_file: /run/cortex/certs/client/ca.crt
    grpc_server_max_recv_msg_size: 104857600
    grpc_server_max_send_msg_size: 104857600
    grpc_server_max_concurrent_streams: 10000
    log_format: json
    log_level: info
distributor:
    pool:
        health_check_ingesters: true
    ha_tracker:
        kvstore:
            multi: {}
    shard_by_all_labels: true
    ring:
        kvstore:
            store: inmemory
            multi: {}
querier:
    active_query_tracker_dir: /data/active-query-tracker
    store_gateway_client:
        tls_enabled: true
        tls_cert_path: /run/cortex/certs/client/tls.crt
        tls_key_path: /run/cortex/certs/client/tls.key
        tls_ca_path: /run/cortex/certs/client/ca.crt
        tls_server_name: cortex-server
ingester_client:
    grpc_client_config:
        max_send_msg_size: 104857600
        tls_enabled: true
        tls_cert_path: /run/cortex/certs/client/tls.crt
        tls_key_path: /run/cortex/certs/client/tls.key
        tls_ca_path: /run/cortex/certs/client/ca.crt
        tls_server_name: cortex-server
ingester:
    lifecycler:
        ring:
            kvstore:
                store: inmemory
                multi: {}
            replication_factor: 1
        num_tokens: 512
        observe_period: 10s
        join_after: 10s
storage:
    engine: blocks
    aws: {}
limits:
    ingestion_rate: 1e+06
    ingestion_rate_strategy: local
    ingestion_burst_size: 2000000
frontend_worker:
    frontend_address: cortex-query-frontend-headless.opni-cluster-system.svc.cluster.local:9095
    grpc_client_config:
        tls_enabled: true
        tls_cert_path: /run/cortex/certs/client/tls.crt
        tls_key_path: /run/cortex/certs/client/tls.key
        tls_ca_path: /run/cortex/certs/client/ca.crt
        tls_server_name: cortex-server
frontend:
    grpc_client_config:
        tls_enabled: true
        tls_cert_path: /run/cortex/certs/client/tls.crt
        tls_key_path: /run/cortex/certs/client/tls.key
        tls_ca_path: /run/cortex/certs/client/ca.crt
        tls_server_name: cortex-server
query_range:
    split_queries_by_interval: 24h0m0s
    align_queries_with_step: true
    cache_results: true
blocks_storage:
    backend: filesystem
    bucket_store:
        sync_dir: /data/tsdb-sync
        bucket_index:
            enabled: true
    tsdb:
        dir: /data/tsdb
        flush_blocks_on_shutdown: true
compactor:
    sharding_ring:
        kvstore:
            store: inmemory
            multi: {}
store_gateway:
    sharding_ring:
        kvstore:
            store: inmemory
            multi: {}
        replication_factor: 1
tenant_federation:
    enabled: true
ruler:
    ruler_client:
        tls_enabled: true
        tls_cert_path: /run/cortex/certs/client/tls.crt
        tls_key_path: /run/cortex/certs/client/tls.key
        tls_ca_path: /run/cortex/certs/client/ca.crt
        tls_server_name: cortex-server
    storage:
        s3: {}
    alertmanager_url: http://opni-alerting:9093
    enable_alertmanager_v2: true
    ring:
        kvstore:
            store: inmemory
            multi: {}
    enable_api: true
ruler_storage:
    backend: filesystem
alertmanager:
    external_url: /api/prom/alertmanager
    sharding_ring:
        kvstore:
            store: inmemory
            multi: {}
        replication_factor: 1
    fallback_config_file: /etc/alertmanager/fallback.yaml
    storage:
        s3: {}
    enable_api: true
    alertmanager_client:
        tls_enabled: true
        tls_cert_path: /run/cortex/certs/client/tls.crt
        tls_key_path: /run/cortex/certs/client/tls.key
        tls_ca_path: /run/cortex/certs/client/ca.crt
        tls_server_name: cortex-server
alertmanager_storage:
    backend: filesystem
runtime_config:
    file: /etc/cortex-runtime-config/runtime_config.yaml
```

Logs:
```
"caller":"blocks_cleaner.go:155","component":"cleaner","err":"12 errors: failed to delete blocks for user: .dockerenv: read bucket index: stat /.dockerenv/bucket-index.json.gz: stat /.dockerenv/bucket-index.json.gz: not a directory; failed to delete blocks for user: bin: upload bucket index: open /bin/bucket-index.json.gz: read-only file system; failed to delete blocks for user: etc: upload bucket index: open /etc/bucket-index.json.gz: read-only file system; failed to delete blocks for user: media: upload bucket index: open /media/bucket-index.json.gz: read-only file system; failed to delete blocks for user: opt: upload bucket index: open /opt/bucket-index.json.gz: read-only file system; failed to delete blocks for user: run: upload bucket index: open /run/bucket-index.json.gz: read-only file system; failed to delete blocks for user: sbin: upload bucket index: open /sbin/bucket-index.json.gz: read-only file system; failed to delete blocks for user: proc: upload bucket index: open /proc/bucket-index.json.gz: no such file or directory; failed to delete blocks for user: sys: upload bucket index: open /sys/bucket-index.json.gz: read-only file system; failed to delete blocks for user: lib: upload bucket index: open /lib/bucket-index.json.gz: read-only file system; failed to delete blocks for user: usr: upload bucket index: open /usr/bucket-index.json.gz: read-only file system; failed to delete blocks for user: var: upload bucket index: open /var/bucket-index.json.gz: read-only file system","level":"error","msg":"failed to run blocks cleanup and maintenance","ts":"2022-10-03T19:36:47.229470281Z"}
{"caller":"compactor.go:584","component":"compactor","level":"info","msg":"discovering users from bucket","ts":"2022-10-03T19:36:47.229688553Z"}

{"caller":"cortex.go:448","err":"invalid service state: Failed, expected: Running, failure: initial blocks synchronization: failed to synchronize TSDB blocks for user .dockerenv: sync block: read bucket index: read bucket index: stat /.dockerenv/bucket-index.json.gz: stat /.dockerenv/bucket-index.json.gz: not a directory","level":"error","module":"store-gateway","msg":"module failed","ts":"2022-10-03T19:34:51.61496571Z"}
```
