### ISSUE TITLE
Global and per-user cortex limits configuration

### ISSUE THREAD

**Issue by kralicky** [rancher/opni#604]
Current limits (defaults):
```yaml
limits:
  ingestion_rate: 25000
  ingestion_rate_strategy: local
  ingestion_burst_size: 50000
  ha_max_clusters: 0
  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 30
  max_metadata_length: 1024
  reject_old_samples: false
  reject_old_samples_max_age: 2w
  ingestion_tenant_shard_size: 0
  max_series_per_query: 100000
  max_samples_per_query: 1000000
  max_series_per_user: 5000000
  max_series_per_metric: 50000
  max_global_series_per_user: 0
  max_global_series_per_metric: 0
  min_chunk_length: 0
  max_metadata_per_user: 8000
  max_metadata_per_metric: 10
  max_global_metadata_per_user: 0
  max_global_metadata_per_metric: 0
  max_chunks_per_query: 2000000
  max_fetched_chunks_per_query: 0
  max_fetched_series_per_query: 0
  max_fetched_chunk_bytes_per_query: 0
  max_query_lookback: 0s
  max_query_length: 0s
  max_query_parallelism: 14
  cardinality_limit: 100000
  max_cache_freshness: 1m
  max_queriers_per_tenant: 0
  ruler_evaluation_delay_duration: 0s
  ruler_tenant_shard_size: 0
  ruler_max_rules_per_rule_group: 0
  ruler_max_rule_groups_per_tenant: 0
  store_gateway_tenant_shard_size: 0
  compactor_blocks_retention_period: 0s
  compactor_tenant_shard_size: 0
  alertmanager_notification_rate_limit: 0
  alertmanager_notification_rate_limit_per_integration: {}
  alertmanager_max_config_size_bytes: 0
  alertmanager_max_templates_count: 0
  alertmanager_max_template_size_bytes: 0
  alertmanager_max_alerts_count: 0
  alertmanager_max_alerts_size_bytes: 0
```

Current overrides: 
```yaml
limits:
  ingestion_burst_size: 2000000
  ingestion_rate: 1e+06
```
