### ISSUE TITLE
Alerting can push invalid recording rules

### ISSUE THREAD

**Issue by alexandreLamarre** [rancher/opni#920]
```
2022-12-16T17:29:20Z DEBUG plugin.alerting alerting/condition_handlers.go:319 name: 0e354f12-2d1b-4ee1-b7b6-6a383b5a307bopni-alerting
interval: 1m
rules:
    - alert: 0e354f12-2d1b-4ee1-b7b6-6a383b5a307b
      expr: opni:custom:prometheus_query{alert_name="sanity-check-metrics",alert_id="0e354f12-2d1b-4ee1-b7b6-6a383b5a307b"}
      for: 30s
      labels:
        conditionId: 0e354f12-2d1b-4ee1-b7b6-6a383b5a307b
      annotations:
        conditionId: 0e354f12-2d1b-4ee1-b7b6-6a383b5a307b
    - record: opni:custom:prometheus_query
      expr: scrape_samples_scraped > bool 0
      labels:
        alert_id: 0e354f12-2d1b-4ee1-b7b6-6a383b5a307b
        alert_name: sanity-check-metrics
```

`alert_name` corresponds one-to-one with the opni alerting name, however the opni alerting name is not guaranteed to be prometheus label safe

**Comment by alexandreLamarre** [comment]
```
groups:
- name: 0e354f12-2d1b-4ee1-b7b6-6a383b5a307bopni-alerting
  interval: 1m
  rules:
    - alert: 0e354f12-2d1b-4ee1-b7b6-6a383b5a307b
      expr: opni:custom:prometheus_query{alert_name="sanity-check-metrics",alert_id="0e354f12-2d1b-4ee1-b7b6-6a383b5a307b"}
      for: 30s
      labels:
        conditionId: 0e354f12-2d1b-4ee1-b7b6-6a383b5a307b
      annotations:
        conditionId: 0e354f12-2d1b-4ee1-b7b6-6a383b5a307b
    - record: opni:custom:prometheus_query
      expr: scrape_samples_scraped > bool 0
      labels:
        alert_id: 0e354f12-2d1b-4ee1-b7b6-6a383b5a307b
        alert_name: sanity-check-metrics
```
is a completely valid rule group as per promtool, so something else is pushing invalid rule groups
